### PR TITLE
Reorder terminate and add secret button

### PR DESCRIPTION
**Pull request by codeimpl**
We decided to reorder terminate and add secret button because of add
secret button will be used more often than the terminate button.

Refs: none

### CODE REVIEW

**Comment by jdragonbae** [comment]
LGTM with nit.

nit : I think we used `Refs: none` instead of `Refs: None`.

**Comment by codeimpl** [comment]
> LGTM with nit.
> 
> nit : I think we used `Refs: none` instead of `Refs: None`.

done! :)

**Review by jdragonbae — APPROVED** [review]
lgtm

**Review by romandev — COMMENTED** [review]
Hmm, as far as I know, we decided to keep the current order. Am I missing something?

**Comment by codeimpl** [comment]
As I remember.. We decide to reorder only adding secret tab and power. Am I wrong??;;;;

**Comment by romandev** [comment]
We decided to drop this patch again.

**Pull request closed without merging**
