### PR TITLE
Fix a build error since m89 rebase

### PR DESCRIPTION
**Pull request by romandev**
Refs: #1123

### CODE REVIEW

**Comment by romandev** [comment]
@jdragonbae @codeimpl gentle ping

**Comment by jdragonbae** [comment]
@romandev lgtm. And I'm not sure the below changes is needed.
Could you please check it?

```
BUILD.gn
+    "//triple_banana/src/org/triple/banana/banana_api/BananaApiLoaderImpl.java",
+    "//triple_banana/src/org/triple/banana/banana_api/export/BananaApiLoader.java",
```

**Comment by romandev** [comment]
@jdragonbae Thank you for review. I've addressed banana_api issue as well.

**Review by jdragonbae — APPROVED** [review]
Thanks for the checking!

**Pull request merged**
